name: Read hello.txt on Push

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Display hello.txt content in log
      - name: Read hello.txt
        run: cat hello.txt
